### ISSUE TITLE
Jumps in RMSD

### ISSUE THREAD

**Issue by juliebehr** [choderalab/kinalysis#16]
Plotting of RMSD of the longest trajectory shows large jumps, even after replacing https://github.com/choderalab/kinalysis/blob/master/make_pdf_summary.py#L103 with

```
calphas = longest_traj.topology.select('name CA')
longest_traj.center_coordinates()
rmsd = md.rmsd(longest_traj,longest_traj,frame=0,atom_indices=calphas)
```

![rmsd](https://cloud.githubusercontent.com/assets/6343082/18917789/c5275f44-8566-11e6-80ac-8a470269ba64.png)

**Comment by juliebehr** [comment]
Also, adding the `precentered` flag and changing that to 

```
calphas = longest_traj.topology.select('name CA')
longest_traj.center_coordinates()
rmsd = md.rmsd(longest_traj,longest_traj,frame=0,atom_indices=calphas,precentered=True)
```

leads to:

```
Traceback (most recent call last):
  File "make_pdf_summary.py", line 401, in <module>
    longest_rmsd(longest_traj, time)
  File "make_pdf_summary.py", line 107, in longest_rmsd
    rmsd = md.rmsd(longest_traj,longest_traj,frame=0,atom_indices=calphas,precentered=True)
  File "mdtraj/rmsd/_rmsd.pyx", line 171, in _rmsd.rmsd (mdtraj/rmsd/_rmsd.c:2785)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by jchodera** [comment]
I think I know why this is happening! Just a moment.

**Comment by jchodera** [comment]
When visualizing the AurA trajectories with Tpx2 last night, I noticed that Tpx2 jumps around quite a bit unless the system is re-imaged back into the box in a manner that minimizes distances between AurA and Tpx2. Fortunately, MDTraj has an [`image_molecules`](http://mdtraj.org/latest/api/generated/mdtraj.Trajectory.html#mdtraj.Trajectory.image_molecules) command that tries to "do the right thing". It's slow, and it may not fix every single frame (it looked like there might still be some infrequent jumps) but I think this is the issue. You can find an example of its use in the [IPython notebook](https://github.com/choderalab/AURKA_UMN/blob/6b6ba53c2e9bdb99de5aa9ce38a4712c7cefcba7/trajectory-viewer/View%20FAH%20trajectory.ipynb) in my [AURKA_UMN PR](https://github.com/choderalab/AURKA_UMN/pull/40).

If this is the problem, the easier thing to do might be to just make sure you only use the kinase selection (`resi 123-388`) for the RMSD calculation, and exclude the Tpx2. I think this would fix that.
